spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace


#    root: debug


camel:
  component:
    servlet:
      mapping:
        context-path: /api/*


server:
  port: 8080

# Local 설정값
---
spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: joyunjae
    password:

# Prod 설정값
---
spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://localhost:aaaa/postgres
    username: joyunjae
    password: ENC(7SxwI7zUSLOchr7GYuyRAQ==)